#!/bin/bash -l

#SBATCH -A dasrepo
#SBATCH --job-name=empirical_coverage_simulations_logscale
#SBATCH --time=36:00:00
#SBATCH --nodes=1
#SBATCH --output=empirical_coverage_simulations_logscale%j.out
#SBATCH --error=empirical_coverage_simulations_logscale%j.err
#SBATCH --exclusive
#SBATCH -q regular
#SBATCH --ntasks-per-node=64
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=butlerj@berkeley.edu
#SBATCH --constraint=cpu

module load R
conda activate isolinesR
export OMP_NUM_THREADS=1

FULL_SAVE_PATH="/pscratch/sd/j/jbbutler/isolines/simulations/empirical/log_scale/"
DF_SAVE_PATH="~/isolines_uq/outputs/simulations/non_extremal/"

Rscript empirical_simulations_logscale.R --save_full_path "$FULL_SAVE_PATH" --save_df_path "$DF_SAVE_PATH" --n_cores 64