#!/bin/bash -l

#SBATCH -A m3318
#SBATCH --job-name=extreme_coverage_simulations
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --output=./logs/extreme_coverage_simulations%j.out
#SBATCH --error=./logs/extreme_coverage_simulations%j.err
#SBATCH --exclusive
#SBATCH -q regular
#SBATCH --ntasks-per-node=64
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=butlerj@berkeley.edu
#SBATCH --constraint=cpu

cd ..
cd R
cd confidence_regions
cd simulation_scripts
cd explorations
cd extreme_explorations
module load R
conda activate isolines
export OMP_NUM_THREADS=1

FULL_SAVE_PATH="/pscratch/sd/j/jbbutler/isolines/simulations/extreme_kde_margs/"
DF_SAVE_PATH="~/isolines_uq/outputs/simulations/extreme_kde_margs/"

Rscript marginal_kde.R --save_full_path "$FULL_SAVE_PATH" --save_df_path "$DF_SAVE_PATH" --n_cores 64