#!/bin/bash -l

#SBATCH -A dasrepo
#SBATCH --job-name=extreme_coverage_simulations_twowaysplit_kde_margs
#SBATCH --time=05:00:00
#SBATCH --nodes=1
#SBATCH --output=./logs/extreme_coverage_simulations_threewaysplit%j.out
#SBATCH --error=./logs/extreme_coverage_simulations_threewaysplit%j.err
#SBATCH --exclusive
#SBATCH -q regular
#SBATCH --ntasks-per-node=64
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=butlerj@berkeley.edu
#SBATCH --constraint=cpu

cd ..
cd R
cd confidence_regions
cd simulation_scripts
module load R
conda activate isolinesR
export OMP_NUM_THREADS=1

FULL_SAVE_PATH="/pscratch/sd/j/jbbutler/isolines/simulations/extremal_twoway_split/kde_margs/"
DF_SAVE_PATH="~/isolines_uq/outputs/simulations/"

Rscript extremal_simulations_twowaysplit_kde_margs.R --save_full_path "$FULL_SAVE_PATH" --save_df_path "$DF_SAVE_PATH" --n_cores 64
