#!/bin/bash -l

#SBATCH -A dasrepo
#SBATCH --job-name=extreme_coverage_simulations
#SBATCH --time=03:00:00
#SBATCH --nodes=1
#SBATCH --output=./logs/rv_tests_simulations%j.out
#SBATCH --error=./logs/rv_tests_simulations%j.err
#SBATCH --exclusive
#SBATCH -q regular
#SBATCH --ntasks-per-node=64
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=butlerj@berkeley.edu
#SBATCH --constraint=cpu

cd ..
cd R
cd confidence_regions
cd simulation_scripts
module load R
conda activate isolinesR
export OMP_NUM_THREADS=1

Rscript projection_bias_variance.R
