#!/bin/bash -l

#SBATCH -A dasrepo
#SBATCH --job-name=extreme_coverage_probability_bias
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --output=./logs/extreme_coverage_probability_bias%j.out
#SBATCH --error=./logs/extreme_coverage_probability_bias%j.err
#SBATCH --exclusive
#SBATCH -q regular
#SBATCH --ntasks-per-node=64
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=butlerj@berkeley.edu
#SBATCH --constraint=cpu

cd ..
cd R
cd confidence_regions
cd simulation_scripts
cd explorations
cd bias_corrections
cd bootstrap_probability_bias
module load R
conda activate isolinesR
export OMP_NUM_THREADS=1

FULL_SAVE_PATH="/pscratch/sd/j/jbbutler/isolines/simulations/extremal_radial_bias_correction/gamma1_0.5_gamma2_0.67/"
DF_SAVE_PATH="~/isolines_uq/outputs/simulations/bias_correction/"

Rscript probability_bias_blowup_coverage.R --save_full_path "$FULL_SAVE_PATH" --save_df_path "$DF_SAVE_PATH" --n_cores 64
